# .github/workflows/bundlesize-compare.yml

on:
  # this action will error unless run in a pr context
  pull_request:

jobs:
  # Build current and upload main.js.map
  # You may replace this with your own build method. All that
  # is required is that the main.js.map be an artifact
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload main.js.map
        uses: actions/upload-artifact@v4
        with:
          name: head-stats
          path: ./dist/main.js.map

  # Build base for comparison and upload main.js.map
  # You may replace this with your own build method. All that
  # is required is that the main.js.map be an artifact
  build-base:
    name: 'Build base'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload main.js.map
        uses: actions/upload-artifact@v4
        with:
          name: base-stats
          path: ./dist/main.js.map

  # run the action against the main.js.map files
  compare:
    name: 'Compare base & head bundle sizes'
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    permissions:
      pull-requests: write
      actions: read
      checks: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: twk3/rollup-size-compare-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: ./head-stats/main.js.map
          base-stats-json-path: ./base-stats/main.js.map

